apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: validator-monitor
  namespace: default
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: bram-vortex-architecture-validator # ΑΛΛΑΞΕ ΑΥΤΟ με το πραγματικό label του service σου
  endpoints:
    - port: http # Ή το όνομα του port που έχει το service (π.χ. 8080)
      path: /actuator/prometheus
      interval: 30s