apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vault-monitor
  namespace: vault
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
  endpoints:
    - port: http
      path: /v1/metrics
      params:
        format: ['prometheus']
      scheme: http
      interval: 30s