apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: analyzer-vault-provider
  namespace: default
spec:
  provider: vault
  parameters:
    roleName: "repo-analyzer-role"
    vaultAddress: "http://vault.vault.svc.cluster.local:8200"
    objects: |
      - objectName: "ANALYZER_USER"
        secretPath: "secret/bram_vortex_db/analyzer"
        secretKey: "an_user"
      - objectName: "ANALYZER_PASSWORD"
        secretPath: "secret/bram_vortex_db/analyzer"
        secretKey: "an_pass"
      - objectName: "GOOGLE_API_KEY"
        secretPath: "secret/ai_key"
        secretKey: "spring.ai.google.genai.api-key"
  secretObjects:
    - secretName: analyzer-secrets-bundle
      type: Opaque
      data:
        - objectName: "ANALYZER_USER"
          key: "an_user"
        - objectName: "ANALYZER_PASSWORD"
          key: "an_pass"
        - objectName: "GOOGLE_API_KEY"
          key: "google-api-key"