apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bram-vortex-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: kong
    # Διατηρούμε το strip-path false για να βλέπει η Java όλο το URL (/dashboard/...)
    konghq.com/strip-path: "false"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          # --- 1. REPO ANALYZER (Υψηλή Προτεραιότητα) ---
          - path: /dashboard/download
            pathType: ImplementationSpecific
            backend:
              service:
                name: repo-analyzer-svc
                port:
                  number: 80
          - path: /dashboard/jobs
            pathType: ImplementationSpecific
            backend:
              service:
                name: repo-analyzer-svc
                port:
                  number: 80
          - path: /dashboard/repos
            pathType: ImplementationSpecific
            backend:
              service:
                name: repo-analyzer-svc
                port:
                  number: 80
          - path: /dashboard/analyze
            pathType: ImplementationSpecific
            backend:
              service:
                name: repo-analyzer-svc
                port:
                  number: 80

          # --- 2. AUTH SERVICE ---
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: bram-vortex-auth-svc
                port:
                  number: 80
          - path: /login/oauth2/code
            pathType: Prefix
            backend:
              service:
                name: bram-vortex-auth-svc
                port:
                  number: 80

          # --- 3. GENERATORS ---
          - path: /terraform/download
            pathType: Prefix
            backend:
              service:
                name: terraform-generator-svc
                port:
                  number: 80
          - path: /ansible/download
            pathType: Prefix
            backend:
              service:
                name: ansible-generator-svc
                port:
                  number: 80
          - path: /terraform/status
            pathType: Prefix
            backend:
              service:
                name: terraform-generator-svc
                port:
                  number: 80
          - path: /ansible/status
            pathType: Prefix
            backend:
              service:
                name: ansible-generator-svc
                port:
                  number: 80

          # --- 4. FRONTEND (ΤΕΛΕΥΤΑΙΟ - Catch-all) ---
          # Πρέπει να είναι στο τέλος για να μη "κλέβει" τα αιτήματα των API
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bram-vortex-frontend-svc
                port:
                  number: 80