apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bram-vortex-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "false" # Απαραίτητο για να λαμβάνει ο Controller ολόκληρο το path
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          # 1. Frontend Route
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bram-vortex-frontend-svc
                port:
                  number: 80

          # 2. Auth Service Routes
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: bram-vortex-auth-svc
                port:
                  number: 80

          # 3. GitHub OAuth Callback
          - path: /login/oauth2/code
            pathType: Prefix
            backend:
              service:
                name: bram-vortex-auth-svc
                port:
                  number: 80

          # 4. Repo Analyzer Routes
          - path: /dashboard/repos
            pathType: Prefix
            backend:
              service:
                name: repo-analyzer-svc
                port:
                  number: 80
          - path: /dashboard/analyze
            pathType: Prefix
            backend:
              service:
                name: repo-analyzer-svc
                port:
                  number: 80
          - path: /dashboard/jobs
            pathType: Prefix
            backend:
              service:
                name: repo-analyzer-svc
                port:
                  number: 80

          # 5. Terraform Generator - ΜΟΝΟ Δημόσια Endpoints (Αυστηρή Λύση)
          - path: /terraform/status
            pathType: Prefix
            backend:
              service:
                name: terraform-generator-svc # Το όνομα από το service.yaml
                port:
                  number: 80 # Η πόρτα του service
          - path: /terraform/download
            pathType: Prefix
            backend:
              service:
                name: terraform-generator-svc
                port:
                  number: 80