apiVersion: apps/v1
kind: Deployment
metadata:
  name: bram-vortex-ansible-generator
  namespace: default
  labels:
    app: bram-vortex-ansible-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bram-vortex-ansible-generator
  template:
    metadata:
      labels:
        app: bram-vortex-ansible-generator
    spec:
      # Χρήση του εξουσιοδοτημένου Service Account
      serviceAccountName: ansible-sa
      containers:
        - name: ansible-generator
          image: christosbramis/bram-vortex-ansible-generator:18f2cc34c126671269bc587a8e918d031b311bd4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            # Endpoint Βάσης Δεδομένων
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-svc:5432/vortexdb"

            # Credentials Βάσης από το CSI Bundle
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ansible-secrets-bundle
                  key: as_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ansible-secrets-bundle
                  key: as_pass

            # Gemini API Key από το CSI Bundle
            - name: SPRING_AI_GOOGLE_GENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ansible-secrets-bundle
                  key: google-api-key

            # JPA Settings
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.PostgreSQLDialect"

          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true

      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "ansible-vault-provider"