apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ansible-vault-provider
  namespace: default
spec:
  provider: vault
  parameters:
    roleName: "ansible-generator-role"
    vaultAddress: "http://vault.vault.svc.cluster.local:8200"
    objects: |
      - objectName: "ANSIBLE_USER"
        secretPath: "secret/bram_vortex_db/ansible"
        secretKey: "as_user"
      - objectName: "ANSIBLE_PASSWORD"
        secretPath: "secret/bram_vortex_db/ansible"
        secretKey: "as_pass"
      - objectName: "GOOGLE_API_KEY"
        secretPath: "secret/ai_key"
        secretKey: "spring.ai.google.genai.api-key"
  secretObjects:
    - secretName: ansible-secrets-bundle
      type: Opaque
      data:
        - objectName: "ANSIBLE_USER"
          key: "as_user"
        - objectName: "ANSIBLE_PASSWORD"
          key: "as-pass"
        - objectName: "GOOGLE_API_KEY"
          key: "google-api-key"