apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: execution-vault-provider
  namespace: default
spec:
  provider: vault
  parameters:
    roleName: "execution-role"
    vaultAddress: "http://vault.vault.svc.cluster.local:8200"
    objects: |
      - objectName: "EXECUTION_USER"
        secretPath: "secret/bram_vortex_db/execution"
        secretKey: "ex_user"
      - objectName: "EXECUTION_PASSWORD"
        secretPath: "secret/bram_vortex_db/execution"
        secretKey: "ex_pass"

  secretObjects:
    - secretName: execution-secrets-bundle
      type: Opaque
      data:
        - objectName: "EXECUTION_USER"
          key: "ex_user"
        - objectName: "EXECUTION_PASSWORD"
          key: "ex_pass"
