apiVersion: apps/v1
kind: Deployment
metadata:
  name: bram-vortex-architecture-validator
  namespace: default
  labels:
    app: bram-vortex-architecture-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bram-vortex-architecture-validator
  template:
    metadata:
      labels:
        app: bram-vortex-architecture-validator
    spec:
      # Χρήση του εξουσιοδοτημένου Service Account
      serviceAccountName: validator-sa
      containers:
        - name: architecture-validator
          image: christosbramis/bram-vortex-architecture-validator:6858dc8d48903d7bf823f1253723efcc3a16528e
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            # Endpoint Βάσης Δεδομένων
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-svc:5432/vortexdb"

            # Credentials Βάσης από το CSI Bundle
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: validator-secrets-bundle
                  key: av_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: validator-secrets-bundle
                  key: av_pass

            # Gemini API Key από το CSI Bundle
            - name: SPRING_AI_GOOGLE_GENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ansible-secrets-bundle
                  key: google-api-key

            # JPA Settings
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.PostgreSQLDialect"

          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true

      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "validator-vault-provider"