apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: validator-vault-provider
  namespace: default
spec:
  provider: vault
  parameters:
    roleName: "architecture-validator-role"
    vaultAddress: "http://vault.vault.svc.cluster.local:8200"
    objects: |
      - objectName: "VALIDATOR_USER"
        secretPath: "secret/bram_vortex_db/validator"
        secretKey: "av_user"
      - objectName: "VALIDATOR_PASSWORD"
        secretPath: "secret/bram_vortex_db/validator"
        secretKey: "av_pass"
      - objectName: "GOOGLE_API_KEY"
        secretPath: "secret/ai_key"
        secretKey: "spring.ai.google.genai.api-key"
  secretObjects:
    - secretName: validator-secrets-bundle
      type: Opaque
      data:
        - objectName: "VALIDATOR_USER"
          key: "av_user"
        - objectName: "VALIDATOR_PASSWORD"
          key: "av_pass"
        - objectName: "GOOGLE_API_KEY"
          key: "google-api-key"